# Generated by Django 4.2.5 on 2023-09-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time', models.TimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maid_deatails',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=100, serialize=False)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('rating', models.FloatField(default=0)),
                ('Date', models.DateField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.time')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('phone_number', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('rating', models.FloatField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.maid_deatails')),
            ],
        ),
    ]
